#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/neryad/src/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/neryad/Documents/Codex/2026-09-20/referenced-chatgpt-conversation-this-is-an/outputs/swipepix"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/neryad/Documents/Codex/2026-09-20/referenced-chatgpt-conversation-this-is-an/outputs/swipepix/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/neryad/Documents/Codex/2026-09-20/referenced-chatgpt-conversation-this-is-an/outputs/swipepix/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDQuMg==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049YzlhNmM0ODQyMw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NzdlMmU5NDc3Mg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/neryad/Documents/Codex/2026-09-20/referenced-chatgpt-conversation-this-is-an/outputs/swipepix/.dart_tool/package_config.json"
